apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cricket-flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aashisaxena15/flask-app-CD.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
