apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cricket-flask-app
  name: cricket-flask-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cricket-flask-app
  type: NodePort
status:
  loadBalancer: {}
